Notes from Stephanie

### 10/18/2018
todo list
- 3.1
add a top taxa table

- 3.2
change CWR - WUS - WEP table to taxon level  

SOS collection, summary table : remove genera

- 3.6
"Orders specific over time" : change orders to packets
"Orders of research over time" : show as a accumulation



notes from annette
- olny accession that have 10,000 extra seeds will make it to USDA

- does BLM call collections assession ?

- the blm will grow seed, it is often contracted out to plant material centers (NRCS)

- one sample is roughly equivalent to 100 seeds.

- impact from the data generated by the SOS progarm

# ongoing questions

limited CWR

? reaching out to BLM about their aquisition and prioritization
  - based on the district level : do they decide how much seed goes where.
  - Leah: what is being collecting

? Confirm of SOS is collecting only BLM land or other lands? federal lands?
   - this seems to be directly tied to the funding source

? in the 2015 paper the term appropriately adapted native plant material was used. How are you defining what is appropriately adapted.

? 2015 paper.(summary of work in Sage Grouse Area) Would it be important to know the summary by different ecological areas.

add a quick map of distribution of hellianthus HELIANTHUS annuus

## Lisa Burke: 2015 transistion order form  Taxonomy and curators

## Include text on most collected and most distrubted taxa  

## add table by taxon similar to the CWR,WUS,WEP

## in K13 - priorety field -P1A how many of those were collected at the Taxon level


```{r}
#install.packages("shiny")
#install.packages("DT")
library(DT)
library(shiny)

DT::datatable(iris)



ui <- basicPage(
  h2("The mtcars data"),
  DT::dataTableOutput("mytable")
)

server <- function(input, output) {
  output$mytable = DT::renderDataTable({
    mtcars
  })
}

shinyApp(ui, server)

```
