\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=1in]{geometry}
\usepackage{hyperref}
\hypersetup{unicode=true,
            pdftitle={Seeds of Success: Collection Diversity, Richness, and Conservation},
            pdfauthor={Colin Khoury, Stephanie Green, Daniel Carver},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{{#1}}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{{#1}}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{{#1}}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{{#1}}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{{#1}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{{#1}}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{{#1}}}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{{#1}}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{{#1}}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{{#1}}}
\newcommand{\ImportTok}[1]{{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{{#1}}}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{{#1}}}}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{{#1}}}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{{#1}}}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{{#1}}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{{#1}}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{{#1}}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{{#1}}}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{{#1}}}}
\newcommand{\BuiltInTok}[1]{{#1}}
\newcommand{\ExtensionTok}[1]{{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{{#1}}}
\newcommand{\RegionMarkerTok}[1]{{#1}}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{{#1}}}}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{{#1}}}}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{{#1}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{{#1}}}}
\newcommand{\NormalTok}[1]{{#1}}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\newcommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}

  \title{Seeds of Success: Collection Diversity, Richness, and Conservation}
    \pretitle{\vspace{\droptitle}\centering\huge}
  \posttitle{\par}
    \author{Colin Khoury, Stephanie Green, Daniel Carver}
    \preauthor{\centering\large\emph}
  \postauthor{\par}
      \predate{\centering\large\emph}
  \postdate{\par}
    \date{June 22, 2018}


\begin{document}
\maketitle

{
\setcounter{tocdepth}{2}
\tableofcontents
}
\section{CheckList}\label{checklist}

\subsection{Datasets}\label{datasets}

\begin{itemize}
\tightlist
\item
  SOSdata = 1
\item
  K13
\item
  Economic Plants =2
\item
  wild crop Relatives = 3
\item
  GRINSOS
\item
  all inventory = 4
\item
  deliveries with taxon = 5
\item
  WEP =6
\end{itemize}

\subsection{connections}\label{connections}

\begin{itemize}
\tightlist
\item
  1\&2 = Of all the SOS seeds collected how many species are considered
  to be Economic plants in north america
\item
  1\&3 = Of all the SOS seeds collected how may species are considiered
  to be Wild Crop Relatives in North America
\item
  4\&2 = Of all the SOS seeds maintained by ARS how many species are
  considered to be Economic plants in north america
\item
  4\&3 = Of all the SOS seeds maintained by ARS how many species are
  considered to be Wild Crop Relatives in north america
\item
  5 = Deliveries: Who received, Reason, data, taxa shipped
\item
  1\&6 = 1\&2 = Of all the SOS seeds collected how many species are
  considered to be World Economic plants
\item
  4\&6 = 1\&2 = Of all the SOS seeds maintained by ARS how many species
  are considered to be World Economic plants
\item
  1 = summary of all taxa collected
\end{itemize}

\section{Goal}\label{goal}

Aim of article- examine and report on the diversity collected via the
BLM SOS program, and its past as well as potential future uses

\section{Introduction}\label{introduction}

Total diversity collected (species, \# of samples, maybe make maps of
spatial distribution of collected diversity) How many are CWR

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#import SOS data }
\NormalTok{sosData <-}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\StringTok{"H:}\CharTok{\textbackslash{}\textbackslash{}}\StringTok{SOS_Project}\CharTok{\textbackslash{}\textbackslash{}}\StringTok{analysisData}\CharTok{\textbackslash{}\textbackslash{}}\StringTok{SOSdata_20180614_forARS.csv"}\NormalTok{)}

\CommentTok{#Find the total number of recorded entries }
\NormalTok{totalSamples <-}\StringTok{ }\KeywordTok{nrow}\NormalTok{(sosData)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "This Seeds of Success program has collected a total of  23577  seed samples. Of which  176  plant families,  1153  plant genus and  2693  unique sub species are represented"
\end{verbatim}

\begin{verbatim}
##                All Accessions Total Number of Familes
## SOS Collection          23577                     176
##                Total Number of Genus Total Number of Sub Species
## SOS Collection                  1153                        2693
\end{verbatim}

This is a better way to make rpint statements

This Seeds of Success program has collected a total of \texttt{23577}
seed samples. Of which
``\texttt{176\ plant\ families}1153\texttt{plant\ genus\ and}2693 unique
sub species are represented.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{families <-}\StringTok{ }\NormalTok{dplyr::}\KeywordTok{arrange}\NormalTok{(uniqueFam1, }\KeywordTok{desc}\NormalTok{(n)) }
\KeywordTok{colnames}\NormalTok{(families) <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"Family"}\NormalTok{, }\StringTok{"Total Number of Accessions"}\NormalTok{)}
\NormalTok{families}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 176 x 2
##    Family           `Total Number of Accessions`
##    <fct>                                   <int>
##  1 ASTERACEAE                               5303
##  2 POACEAE                                  4522
##  3 CYPERACEAE                               1165
##  4 FABACEAE                                 1122
##  5 SCROPHULARIACEAE                         1027
##  6 ROSACEAE                                  977
##  7 CHENOPODIACEAE                            614
##  8 APIACEAE                                  585
##  9 POLYGONACEAE                              582
## 10 ONAGRACEAE                                434
## # ... with 166 more rows
\end{verbatim}

The Seeds of Success program has been collecting seeds since 2000.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# histogram with added parameters}
\NormalTok{sosData <-}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\StringTok{"H:}\CharTok{\textbackslash{}\textbackslash{}}\StringTok{SOS_Project}\CharTok{\textbackslash{}\textbackslash{}}\StringTok{analysisData}\CharTok{\textbackslash{}\textbackslash{}}\StringTok{SOSdata_20180614_forARS.csv"}\NormalTok{)}

\NormalTok{collectionYears <-}\StringTok{ }\NormalTok{sosData$COLL_YR}
\KeywordTok{hist}\NormalTok{(collectionYears,}
  \DataTypeTok{main=}\StringTok{"Accessions collected by SOS"}\NormalTok{,}
  \DataTypeTok{xlab=}\StringTok{"Collection Year"}\NormalTok{,}
  \DataTypeTok{xlim =} \KeywordTok{c}\NormalTok{(}\DecValTok{2000}\NormalTok{,}\DecValTok{2018}\NormalTok{),}
  \DataTypeTok{ylim =} \KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{3500}\NormalTok{),}
  \DataTypeTok{ylab=}\StringTok{"Number of Accession Collected"}\NormalTok{,}
  \DataTypeTok{col=}\StringTok{"blue"}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{sosReport_files/figure-latex/unnamed-chunk-5-1.pdf}

The importance of this collection increased by the fact that many of the
seed taxa that were collected are defined as either Wild Crop Relatives
or World Economic Plants. We will use two datasets that have defined
economically useful plants, Khoury et al 2013, and \emph{get reference
for the WEP dataset received from Daniel}.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# caption="Summary of the SOS collection relative to Econmically Useful and Wild Crop Relatives.", rows.print=15}
\CommentTok{# Create a summary chart showing the total number of accession, total taxa, # of WCR NA, # eco NA, # of economic WEP  }
\CommentTok{# this may be added to also include the data about what's managed by the usda and what's at the NLGRP }
\CommentTok{#}

\CommentTok{# Replace the name column of the sos data so that the "ssp." notation is replaced with "subsp." as defined}
\CommentTok{# by the grin Data base }
\CommentTok{# created a new column that has the same col name as the K13 data set. I will use the col to join on }
\NormalTok{sosData$Taxon <-}\StringTok{ }\KeywordTok{gsub}\NormalTok{(}\StringTok{"ssp."}\NormalTok{,}\StringTok{"subsp."}\NormalTok{, sosData$NAME) }

\CommentTok{#detemine the total number of taxon in dataset }
\NormalTok{sosTotalUnique <-}\StringTok{ }\KeywordTok{nrow}\NormalTok{(}\KeywordTok{unique}\NormalTok{(sosData[}\DecValTok{1}\NormalTok{]))}


\CommentTok{# read in the K13 data }
\NormalTok{K13Data <-}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\StringTok{"H:}\CharTok{\textbackslash{}\textbackslash{}}\StringTok{SOS_Project}\CharTok{\textbackslash{}\textbackslash{}}\StringTok{analysisData}\CharTok{\textbackslash{}\textbackslash{}}\StringTok{CWR_US_inventory_2013_7_10.csv"}\NormalTok{)}

\CommentTok{#detemine the total number of taxon in dataset }
\NormalTok{K13TotalUnique <-}\StringTok{ }\KeywordTok{nrow}\NormalTok{(}\KeywordTok{unique}\NormalTok{(K13Data[}\DecValTok{1}\NormalTok{]))}

\CommentTok{# join the data sets}
\NormalTok{combinedData <-}\StringTok{ }\KeywordTok{join}\NormalTok{(sosData, K13Data, }\DataTypeTok{by=}\StringTok{'Taxon'}\NormalTok{, }\DataTypeTok{type=}\StringTok{'left'}\NormalTok{, }\DataTypeTok{match=}\StringTok{'all'}\NormalTok{)}

\CommentTok{#trim the data so that taxon that do not have values for the K13 specific data columns are dropped. }
\NormalTok{trimCombinedData <-}\StringTok{ }\NormalTok{combinedData[!}\KeywordTok{is.na}\NormalTok{(combinedData$Taxon_w_author), ]}

\CommentTok{#subset all WIld Utilizes Species and calculater total number of species }
\NormalTok{wusSamples <-}\StringTok{ }\KeywordTok{filter}\NormalTok{(trimCombinedData, Type==}\StringTok{ 'WUS'}\NormalTok{)}
\NormalTok{uniqueWUS <-}\StringTok{ }\KeywordTok{n_distinct}\NormalTok{(wusSamples$Taxon)}

\CommentTok{#subset all Crop Wild RElatives and calculater total number of species }
\NormalTok{cwrSamples <-}\StringTok{ }\KeywordTok{filter}\NormalTok{(trimCombinedData, Type==}\StringTok{ 'CWR'}\NormalTok{)}
\NormalTok{uniqueCWR <-}\StringTok{ }\KeywordTok{n_distinct}\NormalTok{(cwrSamples$Taxon)}

\NormalTok{### }
\CommentTok{#Read in the WEP dataset }
\CommentTok{# read in the WEP data }
\NormalTok{WEPData <-}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\StringTok{"H:}\CharTok{\textbackslash{}\textbackslash{}}\StringTok{SOS_Project}\CharTok{\textbackslash{}\textbackslash{}}\StringTok{analysisData}\CharTok{\textbackslash{}\textbackslash{}}\StringTok{EconomicUseCategoriesOfSpecies.csv"}\NormalTok{)}

\NormalTok{## Rename the name column to match the newly created column from the SOS data }
\KeywordTok{colnames}\NormalTok{(WEPData)[}\DecValTok{2}\NormalTok{] <-}\StringTok{ "Taxon"}


\CommentTok{#detemine the total number of taxon in dataset }
\NormalTok{WEPTotalUnique <-}\StringTok{ }\KeywordTok{n_distinct}\NormalTok{(WEPData$taxonomy_species_id)}

\CommentTok{# join the data sets}
\NormalTok{combinedData2 <-}\StringTok{ }\KeywordTok{join}\NormalTok{(sosData, WEPData, }\DataTypeTok{by=}\StringTok{'Taxon'}\NormalTok{, }\DataTypeTok{type=}\StringTok{'left'}\NormalTok{, }\DataTypeTok{match=}\StringTok{'all'}\NormalTok{)}

\CommentTok{#trim the data so that taxon that do not have values for the WEP specific data columns are dropped. }
\NormalTok{trimCombinedData2 <-}\StringTok{ }\KeywordTok{filter}\NormalTok{(combinedData2, !}\KeywordTok{is.na}\NormalTok{(economic_usage_code))}

\CommentTok{#calculate total number of species from }
\NormalTok{uniqueWEP <-}\StringTok{ }\KeywordTok{n_distinct}\NormalTok{(trimCombinedData2$SPECIES)}


\NormalTok{## DEfeine row and column names }
\NormalTok{labelsRow <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"SOS Collection"}\NormalTok{)}
\NormalTok{labelsCol <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{'All Accession'}\NormalTok{, }\StringTok{"Total Number of Taxon"}\NormalTok{, }\StringTok{"Total Number of WUS from K13"}\NormalTok{, }\StringTok{"Total Number of CWR from K13"}\NormalTok{, }\StringTok{"Total Number of WEP"}\NormalTok{)}

\CommentTok{#Initiate an empty dataframe }
\NormalTok{sosSummary2 <-}\StringTok{ }\KeywordTok{data.frame}\NormalTok{()}

\CommentTok{# create the first row of the dataframe }
\NormalTok{sosCollection <-}\StringTok{ }\KeywordTok{c}\NormalTok{(totalSamples, sosTotalUnique, uniqueWUS, uniqueCWR, uniqueWEP)}

\CommentTok{#bind the two df together }
\NormalTok{sosSummary2 <-}\StringTok{ }\KeywordTok{rbind}\NormalTok{(sosSummary2, sosCollection)}
\CommentTok{#define column names and row names }
\KeywordTok{colnames}\NormalTok{(sosSummary2) <-}\StringTok{ }\NormalTok{labelsCol}
\KeywordTok{rownames}\NormalTok{(sosSummary2) <-}\StringTok{ }\NormalTok{labelsRow}
\NormalTok{sosSummary2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                All Accession Total Number of Taxon
## SOS Collection         23577                  5651
##                Total Number of WUS from K13 Total Number of CWR from K13
## SOS Collection                         1001                          737
##                Total Number of WEP
## SOS Collection                 829
\end{verbatim}

\section{Conservation}\label{conservation}

The Seeds of Success program provide the boots on the ground effort in
the collection of seed resources and the program partners with the
Agricultural Research Service of USDA to store, maintian, and distribute
the seeds collected. The Pullman, Washinto ng section of the ARS is the
group primarily responsable for the initial onboarding and entering of
the seeds into the Genetic Resoruce Inventory Network(GRIN) as well as
mainting the seeds in environments that support preservation. Once
within the ARS system the quality of the seed collections are accessed
and samples that are deemed benifical to preserve over an extended
period of time are transfer to the National Laboratory for Genetic
Resource Preservation in Fort Collins, Colorado. The NLRGP specialized
in the long term storage of genetic resources. Below is a few diagrams
and table that illistrate the relationship between the Seeds of Success
program and the ARS.

\begin{itemize}
\item
  How much adopted by Curators, how much ``orphaned'' at W6 - need to
  pull from GRIN Global (examine ``site'') \#Not sure how to answer this
  some at this time
\item
  How much is at NLGRP for long term backup

  \begin{itemize}
  \item
    \begin{itemize}
    \tightlist
    \item
      there are 12959 SOS accessions that are maintianed in long term
      storage backup at NLGRP.*
    \end{itemize}
  \end{itemize}
\item
  Viability/conservation issues (Annette) - proportion easy to germinate
  vs not, other storage issues
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# read in GRIN Accessions }
\NormalTok{grinData <-}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\StringTok{"H:}\CharTok{\textbackslash{}\textbackslash{}}\StringTok{SOS_Project}\CharTok{\textbackslash{}\textbackslash{}}\StringTok{analysisData}\CharTok{\textbackslash{}\textbackslash{}}\StringTok{sosAccessions.csv"}\NormalTok{)}

\CommentTok{# calcualte the total number of features and the total number of taxon }
\NormalTok{totalSamplesGRIN <-}\StringTok{ }\KeywordTok{nrow}\NormalTok{(grinData)}\CommentTok{# why would these two numbers be different? Question for Renee }
\NormalTok{totalName <-}\StringTok{ }\NormalTok{dplyr::}\KeywordTok{n_distinct}\NormalTok{(grinData$Name)}\CommentTok{# why would these two numbers be different? Question for Renee }
\NormalTok{totalTaxon <-}\StringTok{ }\NormalTok{totalName <-}\StringTok{ }\NormalTok{dplyr::}\KeywordTok{n_distinct}\NormalTok{(grinData$Taxon)}


\CommentTok{# join the the GRIN data with the K13 Dataset }
\NormalTok{combinedData3 <-}\StringTok{ }\KeywordTok{join}\NormalTok{(grinData, K13Data, }\DataTypeTok{by=}\StringTok{'Taxon'}\NormalTok{, }\DataTypeTok{type=}\StringTok{'left'}\NormalTok{, }\DataTypeTok{match=}\StringTok{'all'}\NormalTok{)}

\CommentTok{#trim the data so that taxon that do not have values for the K13 specific data columns are dropped. }
\NormalTok{trimCombinedData3 <-}\StringTok{ }\NormalTok{combinedData[!}\KeywordTok{is.na}\NormalTok{(combinedData3$Taxon_w_author), ]}

\CommentTok{#subset all WIld Utilizes Species and calculater total number of species }
\NormalTok{wusSamples3 <-}\StringTok{ }\KeywordTok{filter}\NormalTok{(trimCombinedData3, Type==}\StringTok{ 'WUS'}\NormalTok{)}
\NormalTok{uniqueWUS3 <-}\StringTok{ }\KeywordTok{n_distinct}\NormalTok{(wusSamples3$Taxon)}

\CommentTok{#subset all Crop Wild RElatives and calculater total number of species }
\NormalTok{cwrSamples3 <-}\StringTok{ }\KeywordTok{filter}\NormalTok{(trimCombinedData3, Type==}\StringTok{ 'CWR'}\NormalTok{)}
\NormalTok{uniqueCWR3 <-}\StringTok{ }\KeywordTok{n_distinct}\NormalTok{(cwrSamples3$Taxon)}

\NormalTok{#### Repeat with the WEP DATAset }
\CommentTok{# join the grin data with the WEP data}
\NormalTok{combinedData4 <-}\StringTok{ }\KeywordTok{join}\NormalTok{(grinData, WEPData, }\DataTypeTok{by=}\StringTok{'Taxon'}\NormalTok{, }\DataTypeTok{type=}\StringTok{'left'}\NormalTok{, }\DataTypeTok{match=}\StringTok{'all'}\NormalTok{)}

\CommentTok{#trim the data so that taxon that do not have values for the WEP specific data columns are dropped. }
\NormalTok{trimCombinedData4 <-}\StringTok{ }\KeywordTok{filter}\NormalTok{(combinedData4, !}\KeywordTok{is.na}\NormalTok{(economic_usage_code))}

\CommentTok{#calculate total number of species from }
\NormalTok{uniqueWEP4 <-}\StringTok{ }\KeywordTok{n_distinct}\NormalTok{(trimCombinedData4$Taxon)}


\CommentTok{# create the first row of the dataframe }
\NormalTok{grinCollection <-}\StringTok{ }\KeywordTok{c}\NormalTok{(totalSamplesGRIN, totalTaxon, uniqueWUS3, uniqueCWR3, uniqueWEP4)}

\CommentTok{#bind the two df together }
\NormalTok{sosSummary2 <-}\StringTok{ }\KeywordTok{rbind}\NormalTok{(sosSummary2, grinCollection)}
\KeywordTok{rownames}\NormalTok{(sosSummary2)[}\DecValTok{2}\NormalTok{] <-}\StringTok{ "GRIN Collection"}
\NormalTok{sosSummary2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                 All Accession Total Number of Taxon
## SOS Collection          23577                  5651
## GRIN Collection         13702                  3732
##                 Total Number of WUS from K13 Total Number of CWR from K13
## SOS Collection                          1001                          737
## GRIN Collection                          783                          513
##                 Total Number of WEP
## SOS Collection                  829
## GRIN Collection                1014
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#filter based on the "is backuped" column.  }
\NormalTok{backedUp <-}\StringTok{ }\NormalTok{dplyr::}\KeywordTok{filter}\NormalTok{(grinData, Is.Backed.Up. ==}\StringTok{ 'Y'} \NormalTok{)}
\NormalTok{totaledBackedUp <-}\KeywordTok{nrow}\NormalTok{(backedUp)}
\CommentTok{#filter based on the backup location being NLGRP }
\NormalTok{nlgrpData <-}\StringTok{ }\NormalTok{dplyr::}\KeywordTok{filter}\NormalTok{(backedUp, Backup.Location}\FloatTok{.1} \NormalTok{==}\StringTok{ 'NSSL'} \NormalTok{)}
\NormalTok{totalBackedUp <-}\StringTok{ }\KeywordTok{nrow}\NormalTok{(nlgrpData)}
\NormalTok{## Example of the backed up features that are missing a backup location????}
\NormalTok{#### does this mean an error in data entry, can we assume }
\NormalTok{MissingBackup <-}\StringTok{ }\KeywordTok{count}\NormalTok{(backedUp$Backup.Location}\FloatTok{.1} \NormalTok{)}

\CommentTok{#define the total number of species present in backup}
\NormalTok{totalTaxonNLGRP <-}\StringTok{ }\KeywordTok{n_distinct}\NormalTok{(nlgrpData$Taxon)}

\CommentTok{# apply simliar subsets based on the connection between K13 dataset}

\CommentTok{# join the the GRIN data with the K13 Dataset }
\NormalTok{combinedData5 <-}\StringTok{ }\KeywordTok{join}\NormalTok{(nlgrpData, K13Data, }\DataTypeTok{by=}\StringTok{'Taxon'}\NormalTok{, }\DataTypeTok{type=}\StringTok{'left'}\NormalTok{, }\DataTypeTok{match=}\StringTok{'all'}\NormalTok{)}

\CommentTok{#trim the data so that taxon that do not have values for the K13 specific data columns are dropped. }
\NormalTok{trimCombinedData5 <-}\StringTok{ }\NormalTok{combinedData[!}\KeywordTok{is.na}\NormalTok{(combinedData5$Taxon_w_author), ]}

\CommentTok{#subset all WIld Utilizes Species and calculater total number of species }
\NormalTok{wusSamples5 <-}\StringTok{ }\KeywordTok{filter}\NormalTok{(trimCombinedData5, Type==}\StringTok{ 'WUS'}\NormalTok{)}
\NormalTok{uniqueWUS5 <-}\StringTok{ }\KeywordTok{n_distinct}\NormalTok{(wusSamples5$Taxon)}

\CommentTok{#subset all Crop Wild RElatives and calculater total number of species }
\NormalTok{cwrSamples5 <-}\StringTok{ }\KeywordTok{filter}\NormalTok{(trimCombinedData5, Type==}\StringTok{ 'CWR'}\NormalTok{)}
\NormalTok{uniqueCWR5 <-}\StringTok{ }\KeywordTok{n_distinct}\NormalTok{(cwrSamples5$Taxon)}


\NormalTok{#### Repeat with the WEP DATAset }
\CommentTok{# join the grin data with the WEP data}
\NormalTok{combinedData6 <-}\StringTok{ }\KeywordTok{join}\NormalTok{(nlgrpData, WEPData, }\DataTypeTok{by=}\StringTok{'Taxon'}\NormalTok{, }\DataTypeTok{type=}\StringTok{'left'}\NormalTok{, }\DataTypeTok{match=}\StringTok{'all'}\NormalTok{)}

\CommentTok{#trim the data so that taxon that do not have values for the WEP specific data columns are dropped. }
\NormalTok{trimCombinedData6 <-}\StringTok{ }\KeywordTok{filter}\NormalTok{(combinedData6, !}\KeywordTok{is.na}\NormalTok{(economic_usage_code))}

\CommentTok{#calculate total number of species from }
\NormalTok{uniqueWEP6 <-}\StringTok{ }\KeywordTok{n_distinct}\NormalTok{(trimCombinedData6$Taxon)}




\CommentTok{# create the first row of the dataframe }
\NormalTok{nlgrpCollection <-}\StringTok{ }\KeywordTok{c}\NormalTok{(totalBackedUp, totalTaxonNLGRP, uniqueWUS5, uniqueCWR5, uniqueWEP6)}

\CommentTok{#bind the two df together }
\NormalTok{sosSummary2 <-}\StringTok{ }\KeywordTok{rbind}\NormalTok{(sosSummary2, nlgrpCollection)}
\KeywordTok{rownames}\NormalTok{(sosSummary2)[}\DecValTok{3}\NormalTok{] <-}\StringTok{ "NLGRP Collection"}
\NormalTok{sosSummary2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                  All Accession Total Number of Taxon
## SOS Collection           23577                  5651
## GRIN Collection          13702                  3732
## NLGRP Collection          9893                  3124
##                  Total Number of WUS from K13 Total Number of CWR from K13
## SOS Collection                           1001                          737
## GRIN Collection                           783                          513
## NLGRP Collection                          802                          522
##                  Total Number of WEP
## SOS Collection                   829
## GRIN Collection                 1014
## NLGRP Collection                 826
\end{verbatim}

\section{Uses}\label{uses}

Report on distributions out of NPGS of materials from SOS, by year, by
receiver, by species or taxonomic group

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{deliveryData <-}\KeywordTok{read.csv}\NormalTok{(}\StringTok{"H:}\CharTok{\textbackslash{}\textbackslash{}}\StringTok{SOS_Project}\CharTok{\textbackslash{}\textbackslash{}}\StringTok{analysisData}\CharTok{\textbackslash{}\textbackslash{}}\StringTok{sosOrdersTotal.csv"}\NormalTok{)}
\KeywordTok{print}\NormalTok{(deliveryData)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    COUNT order_type_code category_code
## 1   2482              TR           STA
## 2    125              DI          FIND
## 3    501              DI          UFED
## 4   2180              DI          FPRU
## 5      9              GR           STA
## 6   6381              DI          UIND
## 7    224              RE          UARS
## 8    804              NR          UIND
## 9      9              NR          FIND
## 10    46              RE           STA
## 11     3              IO          UIND
## 12   101              BA          FGEN
## 13    68              DI          FGEN
## 14   740              GR          UARS
## 15    36              OB          UARS
## 16   847              DI          FCOM
## 17  4955              DI           STA
## 18    10              OB           STA
## 19  1044              IO          UARS
## 20  6885              TR          UARS
## 21    11              NR          UCOM
## 22     1              IO          UPRU
## 23    20              NR          UPRU
## 24     1              NR          FCOM
## 25    15              NR           STA
## 26 15831              BA          UARS
## 27   743              DI          UARS
## 28  1627              DI          UCOM
## 29  1360              DI          UPRU
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# select all rows that were delivered to ARS locations }
\NormalTok{ars <-}\StringTok{ }\KeywordTok{filter}\NormalTok{(deliveryData, category_code ==}\StringTok{ "UARS"}\NormalTok{)}
\NormalTok{ars <-}\StringTok{ }\NormalTok{ars[,}\DecValTok{1}\NormalTok{:}\DecValTok{2}\NormalTok{]}
\NormalTok{labelsColumns <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{'Number of Deliveries'}\NormalTok{, }\StringTok{"Reason for Delivery"} \NormalTok{)}
\NormalTok{values2 <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"Replenishment"}\NormalTok{, }\StringTok{"Germination"}\NormalTok{, }\StringTok{"Observation"}
                              \NormalTok{,}\StringTok{"Information only"}\NormalTok{, }\StringTok{"Transfer"}\NormalTok{, }\StringTok{"Backup"}
                              \NormalTok{,}\StringTok{"Distribution"}\NormalTok{)}
\NormalTok{ars$order_type_code <-}\StringTok{ }\NormalTok{values2}

\KeywordTok{colnames}\NormalTok{(ars) <-}\StringTok{ }\NormalTok{labelsColumns}
\KeywordTok{colnames}\NormalTok{(ars)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Number of Deliveries" "Reason for Delivery"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ars<-}\StringTok{ }\NormalTok{ars[}\KeywordTok{order}\NormalTok{(-ars$}\StringTok{'Number of Deliveries'}\NormalTok{),]}

\KeywordTok{print}\NormalTok{(ars)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Number of Deliveries Reason for Delivery
## 6                15831              Backup
## 5                 6885            Transfer
## 4                 1044    Information only
## 7                  743        Distribution
## 2                  740         Germination
## 1                  224       Replenishment
## 3                   36         Observation
\end{verbatim}

Investigate reasons for use- narrative description in GRIN Global How
many are CWR and impacts

\section{Discussion}\label{discussion}

\begin{itemize}
\tightlist
\item
  W6 doesnt have the resources to manage seeds indefinitely
\item
  Constraints / challenges to adopting more wild plants
\item
  Constraints with regard to getting materials into long term storage
\item
  Challenge of not having seed testing techniques/rules worked out for
  species
\end{itemize}

\subsection{Quarterly Results}\label{quarterly-results}


\end{document}
